name: sch550-root

include:
  - path: db/compose.yaml # File server
  - path: supabase/compose.yaml # Supabase

services:
    frontend:
        image: paranoidphantom/school.550:latest
        build: .
        restart: unless-stopped
        volumes:
            - .env:/usr/src/app/.env
        ports:
            - 3000:3000
    nginx:
        image: paranoidphantom/nginx.school.550:latest
        build: ./nginx
        restart: unless-stopped
        depends_on:
            - frontend
        ports:
            - 80:80
            - 443:443
        volumes:
            - /etc/letsencrypt/live:/etc/letsencrypt/live
    dozzle:
      image: amir20/dozzle:latest
      restart: unless-stopped
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 8080:8080