name: sch550-build-prod

include:
  - path: db/compose.yaml # File server

services:
    uiprod:
        image: ghcr.io/paranoidphantom/school.550:latest
        build: .
        restart: unless-stopped
        platform: linux/amd64
        volumes:
            - ./.env.prod:/usr/src/app/.env
    nginx:
        image: ghcr.io/paranoidphantom/nginx.school.550:latest
        build: ./nginx
        restart: unless-stopped
        platform: linux/amd64
        ports:
            - 80:80
            - 443:443
        volumes:
            - /etc/letsencrypt/live:/etc/letsencrypt/livech