name: sch550-build-preview

include:
  - path: db/compose.yaml # File server

services:
    uipreview:
        image: paranoidphantom/school.550:preview
        build: .
        restart: unless-stopped
        volumes:
            - ./.env.preview:/usr/src/app/.env
    nginx:
        image: paranoidphantom/nginx.school.550:latest
        build: ./nginx
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - /etc/letsencrypt/live:/etc/letsencrypt/live