global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'uipreview'
    static_configs:
      - targets: ['uipreview:3000']
  - job_name: 'uiprod'
    static_configs:
      - targets: ['uiprod:3000']