api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

http:
  routers:
    web:
      entryPoints:
        - "web"
      rule: "Host(`db.portaltest.ort.spb.ru`)"
      service: "app"
      middlewares:
        - "https-redirect"
    websecure:
      entryPoints:
        - "websecure"
      rule: "Host(`db.portaltest.ort.spb.ru`)"
      service: "app"
      tls:
        certResolver: "letsencrypt"
  
  services:
    app:
      loadBalancer:
        servers:
          - url: "http://app:3000"
  
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: "https"

certificatesResolvers:
  letsencrypt:
    acme:
      email: andrei.hudalla@outlook.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: "web"