name: sch550-fs

services:
    fs:
        image: paranoidphantom/db.school.550:latest
        build: .
        restart: unless-stopped
        volumes:
            - .env:/usr/src/app/.env
            - storage:/usr/src/app/storage
    fs_ftp:
        image: delfer/alpine-ftp-server
        restart: unless-stopped
        ports:
            - 21:21
            - 21000-21010:21000-21010
        environment:
            - "ADDRESS=${IP}"
            - "USERS=${AUTHENTICATION}"
            - "TLS_CERT=/etc/letsencrypt/live/portaltest.ort.spb.ru/fullchain.pem"
            - "TLS_KEY=/etc/letsencrypt/live/portaltest.ort.spb.ru/privkey.pem"
        volumes:
            - storage:/home/ftp/storage
            - /etc/letsencrypt/live/portaltest.ort.spb.ru/fullchain.pem:/etc/letsencrypt/live/portaltest.ort.spb.ru/fullchain.pem
            - /etc/letsencrypt/live/portaltest.ort.spb.ru/privkey.pem:/etc/letsencrypt/live/portaltest.ort.spb.ru/privkey.pem

volumes:
    storage: