services:
    app:
        image: paranoidphantom/db.school.550:latest
        build: .
        restart: always
        volumes:
            - .env:/usr/src/app/.env
            - storage:/usr/src/app/storage
    nginx:
        image: nginx:latest
        restart: always
        depends_on:
            - app
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - /etc/letsencrypt/live/portaltest.ort.spb.ru/fullchain.pem:/etc/letsencrypt/live/portaltest.ort.spb.ru/fullchain.pem
            - /etc/letsencrypt/live/portaltest.ort.spb.ru/privkey.pem:/etc/letsencrypt/live/portaltest.ort.spb.ru/privkey.pem
    watchtower:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always
        command: --interval 30
    ftp:
        image: delfer/alpine-ftp-server
        restart: always
        ports:
            - 21:21
            - 21000-21010:21000-21010
        environment:
            - "ADDRESS=${IP}"
            - "USERS=${AUTHENTICATION}"
            - "TLS_CERT=/etc/letsencrypt/live/portaltest.ort.spb.ru/fullchain.pem"
            - "TLS_KEY=/etc/letsencrypt/live/portaltest.ort.spb.ru/privkey.pem"
        volumes:
            - storage:/home/ftp/storage
            - /etc/letsencrypt/live/portaltest.ort.spb.ru/fullchain.pem:/etc/letsencrypt/live/portaltest.ort.spb.ru/fullchain.pem
            - /etc/letsencrypt/live/portaltest.ort.spb.ru/privkey.pem:/etc/letsencrypt/live/portaltest.ort.spb.ru/privkey.pem

volumes:
    storage: