

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."content" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "md" "text" DEFAULT ''::"text" NOT NULL,
    "restricted" boolean DEFAULT false NOT NULL,
    "slug" "text" DEFAULT ''::"text" NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."content" OWNER TO "supabase_admin";


ALTER TABLE "public"."content" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."content_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."header-links" (
    "id" bigint NOT NULL,
    "groupName" "text" DEFAULT ''::"text" NOT NULL,
    "height" numeric DEFAULT '100'::numeric NOT NULL,
    "index" numeric DEFAULT '0'::numeric NOT NULL,
    "logic" "jsonb"
);


ALTER TABLE "public"."header-links" OWNER TO "supabase_admin";


ALTER TABLE "public"."header-links" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."header-links_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."registration-links" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "activated_at" timestamp with time zone,
    "initial-perms" "text"[] DEFAULT '{}'::"text"[] NOT NULL,
    "metadata" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL
);


ALTER TABLE "public"."registration-links" OWNER TO "supabase_admin";


ALTER TABLE "public"."registration-links" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."registration-links_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."required-announcements" (
    "id" bigint NOT NULL,
    "index" numeric DEFAULT '0'::numeric NOT NULL,
    "description" "text",
    "image_url" "text",
    "label" "text",
    "route" "text"
);


ALTER TABLE "public"."required-announcements" OWNER TO "supabase_admin";


ALTER TABLE "public"."required-announcements" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."required-announcements_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "perms" "text"[]
);


ALTER TABLE "public"."users" OWNER TO "supabase_admin";


ALTER TABLE ONLY "public"."content"
    ADD CONSTRAINT "content_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."header-links"
    ADD CONSTRAINT "header-links_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."registration-links"
    ADD CONSTRAINT "registration-links_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."required-announcements"
    ADD CONSTRAINT "required-announcements_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



CREATE POLICY "Enable read access for all users" ON "public"."content" FOR SELECT USING (("restricted" = false));



CREATE POLICY "Enable read access for all users" ON "public"."header-links" FOR SELECT USING (true);



ALTER TABLE "public"."content" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."header-links" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."registration-links" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."required-announcements" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";





GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";
























































































































































































































GRANT ALL ON TABLE "public"."content" TO "postgres";
GRANT ALL ON TABLE "public"."content" TO "anon";
GRANT ALL ON TABLE "public"."content" TO "authenticated";
GRANT ALL ON TABLE "public"."content" TO "service_role";



GRANT ALL ON SEQUENCE "public"."content_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."content_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."content_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."content_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."header-links" TO "postgres";
GRANT ALL ON TABLE "public"."header-links" TO "anon";
GRANT ALL ON TABLE "public"."header-links" TO "authenticated";
GRANT ALL ON TABLE "public"."header-links" TO "service_role";



GRANT ALL ON SEQUENCE "public"."header-links_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."header-links_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."header-links_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."header-links_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."registration-links" TO "postgres";
GRANT ALL ON TABLE "public"."registration-links" TO "anon";
GRANT ALL ON TABLE "public"."registration-links" TO "authenticated";
GRANT ALL ON TABLE "public"."registration-links" TO "service_role";



GRANT ALL ON SEQUENCE "public"."registration-links_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."registration-links_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."registration-links_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."registration-links_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."required-announcements" TO "postgres";
GRANT ALL ON TABLE "public"."required-announcements" TO "anon";
GRANT ALL ON TABLE "public"."required-announcements" TO "authenticated";
GRANT ALL ON TABLE "public"."required-announcements" TO "service_role";



GRANT ALL ON SEQUENCE "public"."required-announcements_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."required-announcements_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."required-announcements_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."required-announcements_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "postgres";
GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
