name: Dev branch deployment

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-20.04
        environment: production

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Create .env file
              run: |
                  echo '${{ secrets.ENV_FILE }}' > .env
            - name: Run deployment script
              run: |
                  npm run deploy-master
