name: "Preview@dev"

on:
    push:
        branches: [dev]

jobs:
    build:
        name: "DEV~${{ github.run_id }}"
        runs-on: ubuntu-20.04
        environment: dev

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Create .env file
              run: |
                  echo '${{ secrets.ENV_FILE }}' > .env
            - name: "Login to GitHub Container Registry"
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{github.actor}}
                  password: ${{secrets.GITHUB_TOKEN}}

            - name: Run deployment script
              run: |
                  npm run deploy-dev
