name: Docker build

run-name: Docker production build

on:
    push:
        branches:
            - "master"
            - "dev"
            - "migrate-to-self-hosting"

jobs:
    docker:
        runs-on: personal
        environment: production
        concurrency: production
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Run build
              run: |
                  docker compose build
            - name: Push build
              run: |
                  docker compose push