name: Docker compose refresh

run-name: Docker compose refresh

on:
    push:
        branches:
            - "master"
            - "dev"

jobs:
    docker:
        runs-on: self-hosted
        steps:
            - name: Extract branch name
              shell: bash
              run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
              id: extract_branch
            - name: Go to working directory
              run: cd /home/fred/school.550
            - name: Authenticate with infisical
              run: export INFISICAL_TOKEN=$(infisical login --method=universal-auth --client-id=${{ secrets.MACHINE_IDENTITY_CLIENT_ID }} --client-secret=${{ secrets.MACHINE_IDENTITY_CLIENT_SECRET }} --silent --plain
            - name: Pull fresh environment variables
              run: infisical export --env=${{ steps.extract_branch.outputs.branch }} --format=dotenv-export > ./.env.${{ steps.extract_branch.outputs.branch }}
            - name: Pull fresh images
              run: docker compose pull
            - name: Shutdown application
              run: docker compose down --remove-orphans
            - name: Run application
              run: docker compose up -d