name: Image refresh

run-name: Deployment@${{ github.ref_name }} - ${{ github.run_id }}

on:
    push:
        branches:
            - "master"
            - "dev"

jobs:
    Deploy:
        runs-on: self-hosted
        environment: ${{ github.ref_name }}
        steps:
            - name: Extract branch name
              shell: bash
              run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
              id: extract_branch
            - name: Make copy of .env for Nuxt runtime config
              run: cp .env.${{ steps.extract_branch.outputs.branch }} .env
              working-directory: /home/fred/school.550
            - name: Pull fresh images
              run: docker compose pull
              working-directory: /home/fred/school.550
            - name: Run application
              run: docker compose up -d --no-deps
              working-directory: /home/fred/school.550